#SPDX-License-Identifier: MIT-0
---
# vars file for roles/shipping
component: shipping
app_path: /app
schema_setup: mysql
schema_files:
  - schema
  - master-data
  - app-user
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-dev/data/shipping token={{vault_token}} url=https://vault-internal.codedeploywithbharath.tech validate_certs=false')}}"