- name: RoboShop Project Playbook
  hosts: all
  become: true
  vars:
    role_name:
    - frontend
    - mongod
    - catalogue
    - redis
    - cart
    - mysql
    - shipping
    - rabbitmq
    - payment
    - dispatch
  roles:
    - "{{ role_name }}"