
- name: Disable default nginx module
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: App Prerequsites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq


- name: Restart service Nginx, in all cases
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true