#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rabbitmq

- name: COpy Repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo


- name: Install RabbitMq Server
  ansible.builtin.dnf:
    name: rabbitmq-server


- name: Start RabbitMQ service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: yes


- name: Create application user
  ansible.builtin.shell: rabbitmqctl add_user {{ secrets.RABBITMQ_USER }} {{ secrets.RABBITMQ_PASS }}  ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"