#SPDX-License-Identifier: MIT-0
---
# vars file for roles/redis
component: redis
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-dev/data/redis token={{vault_token}} url=http://vault-internal.codedeploywithbharath.tech:8200 validate_certs=false')}}"