#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/catalogue
- name: Setup NodeJs Service
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs



- name: Copy Service file
  ansible.builtin.template:
    src: "catalogue.service"
    dest: /etc/systemd/system/catalogue.service

- name: COpy MongoDB repo file
  ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
      name: mongodb-mongosh
      state: latest

- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongod.codedeploywithbharath.tech </app/db/master-data.js


- name: Start Service
  ansible.builtin.systemd_service:
    name: catalogue.service
    state: restarted
    enabled: true
    daemon-reload: true