#SPDX-License-Identifier: MIT-0
---
# vars file for roles/dispatch
component: dispatch
app_path: /app
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-dev/data/dispatch token={{vault_token}} url=http://vault-internal.codedeploywithbharath.tech:8200 validate_certs=false')}}"