
- name: COpy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Print the current working directory
  ansible.builtin.shell: ls
  args:
    chdir: "{{ app_path }}"
  register: pwd_result

- name: Print the current working directory
  ansible.builtin.debug:
    msg: "The current working directory is: {{ pwd_result.stdout }}"

- name: Ensure master.js has appropriate permissions
  ansible.builtin.file:
    path: "{{ app_path }}/db/master.js"
    mode: "0644"

- name: Verify db/master.js file exists
  ansible.builtin.shell: ls -l db/master.js
  args:
    chdir: "{{ app_path }}"



- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongod.codedeploywithbharath.tech < db/master.js
  args:
    chdir: "{{ app_path }}"