
- name: COpy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Print the current working directory
  ansible.builtin.shell: pwd
  args:
    chdir: "{{ app_path }}"


- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongod.codedeploywithbharath.tech </db/master.js
  args:
    chdir: "{{ app_path }}"
