#SPDX-License-Identifier: MIT-0
---
# vars file for roles/catalogue
component: catalogue
app_path: /app
schema_setup: mongo
schema_files:
  - master-data

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-dev/data/catalogue token={{vault_token}} url=https://vault-internal.codedeploywithbharath.tech validate_certs=false')}}"