#SPDX-License-Identifier: MIT-0
---
# vars file for roles/rabbitmq
component: rabbitmq
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-dev/data/rabbitmq token={{vault_token}} url=https://vault-internal.codedeploywithbharath.tech validate_certs=false')}}"